### ISSUE TITLE
Expected behavior when merging queries with parameters 

### ISSUE THREAD

**Issue by kennyjwilli** [edn-query-language/eql#12]
What is the expected behavior when calling `merge-queries` with a property that has parameters? I would expect a similar behavior to Clojure's `merge`, however that is not what I'm seeing. 

This works as expected.
```clojure
(eql/merge-queries [(list :a {:x 1})] [(list :a {:x 1})])
=> [(:a {:x 1})]
```

I would have expected `:a` to have the `{:x 1}` param map added to it. `nil` is a very strange return.
```clojure
(eql/merge-queries [:a] [(list :a {:x 1})])
=> nil
```

```clojure
(eql/merge-queries [(list :a {:x 1})] [(list :a {:x 2 :y 3})])
=> nil
```

**Comment by awkay** [comment]
As far as I'm concerned those two queries are not legally mergeable: they have diff parameters, which indicate a desire for different result. Combining them makes no sense. A query also returns a map, so having them in the same EQL expression is also non-sensical. You must *split* such an EQL expression ( one that contains duplicate query keys with differing parameters), not merge it.
