### ISSUE TITLE
Support for string keys?

### ISSUE THREAD

**Issue by kennyjwilli** [edn-query-language/eql#19]
The EQL specification [defines properties](https://edn-query-language.org/eql/1.0.0/specification.html#_properties) as "Clojure keywords; they can be simple or qualified keywords, and they express the property been requested." When only working with Clojure data, this definition makes sense. There could be cases where external data is given as a JSON document where keywordizing keys is not preferable (i.e., certain keys are not valid keywords), yet the EQL format still has merit. 

What are the authors' thoughts on adding support for string properties? For example, the below query would be valid. 

```clojure
;; Query 
["a" {"b" ["c"]}]

;; AST 
(query->ast ["a" {"b" ["c"]}])
=>
{:type :root,
 :children [{:type :prop, :dispatch-key "a", :key "a"}
            {:type :join,
             :dispatch-key "b",
             :key "b",
             :query ["c"],
             :children [{:type :prop, :dispatch-key "c", :key "c"}]}]}
```

**Comment by awkay** [comment]
My take would be "convert the JSON request to clj data, then process those strings into keywords". That way you don't lose namespacing, which is also important: ["a/b"] -> [:a/b].  IMO it is an external concern that is fixable with a simple wrapper and should not be a concern of EQL itself.

**Comment by wilkerlucio** [comment]
I agree with @awkay on this.
