### ISSUE TITLE
merge-queries doesn't appear to handle joins with params

### ISSUE THREAD

**Issue by jmerrifield** [edn-query-language/eql#21]
`merge-queries` produces output which I think is unexpected, when provided joins with params:

```clj
(merge-queries '[{(:join-key {:with "params"}) [:sub-query]}] [:other])

=> [({:join-key [:sub-query]} {:with "params"}) :other]
```

I appreciate that, as discussed in #12, merging queries with params might not make sense, but in my use case I'm guaranteed not to attempt to query the same field multiple times with different params.

**Comment by awkay** [comment]
```
(eql/query->ast '[({:join-key [:sub-query]} {:with "params"}) :other])
=>
{:type :root,
 :children [{:type :join,
             :dispatch-key :join-key,
             :key :join-key,
             :query [:sub-query],
             :children [{:type :prop, :dispatch-key :sub-query, :key :sub-query}],
             :params {:with "params"},
             :meta {:line 1, :column 160}}
            {:type :prop, :dispatch-key :other, :key :other}]}
```

params can be placed on the keyword of a join, or around the join itself.

**Comment by jmerrifield** [comment]
You're right, this works fine, and my error was elsewhere. Thanks for the response!
