### ISSUE TITLE
Support for "multiple idents" an implementation detail?

### ISSUE THREAD

**Issue by geodrome** [edn-query-language/eql#22]
EQL officially supports idents and joining on idents, but it doesn't seem to support "multiple idents" and joining on "multiple idents." **I've found a straightforward way to do it, but I'm concerned I might be relying on an implementation detail.**

I want to do something similar to `pull-many` in Datomic. I can use a vector of idents in place of a single ident and I get something that works:

```clojure
(e/query->ast [[[:customer/id 123] [:customer/id 456]]])

=> {:type :root, :children [{:type :prop, :dispatch-key [:customer/id 123],
                 :key [[:customer/id 123] [:customer/id 456]]}]}
``` 

The `:key` will contain the multiple idents. Same behavior when joining:

```clojure
(e/query->ast [{[[:customer/id 123] [:customer/id 456]]
                [:customer/name :customer/email]}])
=>
{:type :root,
 :children [{:type :join,
             :dispatch-key [:customer/id 123],
             :key [[:customer/id 123] [:customer/id 456]],
             :query [:customer/name :customer/email],
             :children [{:type :prop, :dispatch-key :customer/name, :key :customer/name}
                        {:type :prop, :dispatch-key :customer/email, :key :customer/email}]}]}
``` 

**This works for me, but I am wondering if I am relying on an implementation detail that may change underneath me. Please advise.**

**Comment by wilkerlucio** [comment]
Hello @geodrome .

This is the first time I see anyone doing something like this. First, EQL is kinda agnostic about how you process it, so as long as you get the right syntax, it's fine. That said, I think it's worth pointing out that `[[:customer/id 123] [:customer/id 456]]` isn't considered an `ident`, it's a complex key instead. You can check by:

![CleanShot 2024-12-17 at 09 43 05@2x](https://github.com/user-attachments/assets/c97c09b5-6684-47d8-8235-4a9c199444b8)

Now talking about how to accomplish a pull-many thing, my recommendation is to use the approach Pathom does (not sure if you are using it, or writing your own thing, but the idea can be ported). So, in Pathom 3, you can achieve multiple entries as follows:

```
(p.eql/process env {:customers [{:customer/id 123} {:customer/id 456}]} [{:customers [:customer/name :customer/email]}])
```

So, as you can see, in that example, we provide initial data via an entity (in Pathom 3, although I still support idents, I found myself preferring providing initial entity data, which allows for a much richer initial point, versus idents which can only provide a single attribute). Then we navigate and process the collection already, which you can just provide a single attribute or as many as make sense in your context.

I hope this can help clarify the approach. I'm closing the issue, but I'm happy to keep discussing it if you still have questions.

**Comment by geodrome** [comment]
Thanks for the quick reply.

I've considered doing something similar to what you do with pathom (I'm building my own thing), but I'm still debating.

I understand that `[[:customer/id 123] [:customer/id 456]]` isn't technically an ident. But do you know if I can reliably expect the `:key` will contain the multiple vectors (which for me represent idents) or if this is just an implementation detail that happens to work right now, but isn't guaranteed.
