### ISSUE TITLE
Improve clarity in README

### ISSUE THREAD

**Issue by drewverlee** [edn-query-language/eql#4]
It's a minor thing, but the following is hard to understand:

> The following sections explain the features provided by the EQL syntax and the common usages of it. Along with code examples from the transactions, after that, we are going to provide the AST data that’s equivalent to the transaction, the AST is the recommended format to transform EQL transactions programmatically. The EQL format is great for users and interfaces, but to transform is easier if you don’t have to deal with the syntax details/ambiguities. The EQL library provides functions to convert from and to AST from EQL.

Maybe:

The following sections explain the features provided by the EQL syntax and the common usages of it. The following code examples show transactions along with their AST data equivalents. The AST is the recommended format to transform EQL transactions programmatically because [TODO]. 

[It's unclear how to interpret this part]
The EQL format is great for users and interfaces, but to transform is easier if you don’t have to deal with the syntax details/ambiguities. 

[a minor change]
The EQL library provides functions fo bidirectional conversation between AST and EQL.

Assuming that it supports it both ways, which is how I took the original wording.

**Comment by awkay** [comment]
Updated, thanks.
