### ISSUE TITLE
How are graphqls subscriptions represented in EQL?

### ISSUE THREAD

**Issue by orolle** [edn-query-language/eql#8]
I look for the equivalent of graphql subscription in EQL. 
How are graphql subscriptions represented in EQL?

**Comment by awkay** [comment]
Please do not use issues for questions. Use Clojurians Slack, either the #pathom or #fulcro channel.

Short answer: EQL is about representation, not interpretation. Subscriptions are "queries that are automatically fulfilled"...interpretation of that in the context of EQL is up to specific libraries that use it.
